name: OkMock PR Checker

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      ## Android Part
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle
        uses: actions/cache@v2
        env:
          cache-name: gradle
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('build.gradle') }}
          restore-keys: |
            gradle-${{ hashFiles('build.gradle') }}
            gradle-

      - name: Build with Gradle
        run: cd android_okmock && ./gradlew build

      ## Server Part
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Build Go Binary
        run: |
          cd okmock-cli
          go build -v .

      ## Flutter Part
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5'

      - name: Check Flutter
        run: |
          cd flutter_okmock
          cd okmock
          flutter pub publish --dry-run
          flutter test
