name: OkMock CLI release

on:
  push:
    branches: [main]
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd okmock-cli
          go build -v .

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
          workdir: okmock-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
